# pipelines.yml
################################################################################
# Version: 26.10.1                                                               #
# Required: True                                                               #
# Description: Defines the pfELK Logstash pipeline.                            #
################################################################################

- pipeline.id: pfelk
  path.config: "/etc/pfelk/conf.d/*.pfelk"
  pipeline.ecs_compatibility: v8
